#!/bin/bash
MESOS_BUILD_DIR="/Users/nnielsen/scratchpad/mesos/build"
PYTHONPATH="/3rdparty/distribute-0.6.26/dist/distribute-0.6.26-py2.7.egg:/Users/nnielsen/scratchpad/mesos/build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/python/dist/protobuf-2.5.0-py2.7.egg:/Users/nnielsen/scratchpad/mesos/build/src/python/dist/mesos-0.18.0-py2.7-macosx-10.9-intel.egg" python hydra-mesos.py "$@"
